### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by nailperry-zd** [wonderkiln/CameraKit-Android#107]
```
java.lang.NullPointerException: Attempt to write to field 'java.util.LinkedHashMap$LinkedEntry java.util.LinkedHashMap$LinkedEntry.prv' on a null object reference
	at java.util.LinkedHashMap.postRemove(LinkedHashMap.java:292)
	at java.util.HashMap.remove(HashMap.java:629)
	at android.hardware.Camera$Parameters.put(Camera.java:3004)
	at android.hardware.Camera$Parameters.set(Camera.java:2984)
	at android.hardware.Camera$Parameters.setPreviewSize(Camera.java:3078)
	at com.flurgle.camerakit.Camera1.adjustCameraParameters(Camera1.java:376)
	at com.flurgle.camerakit.Camera1.access$200(Camera1.java:30)
	at com.flurgle.camerakit.Camera1$1.onSurfaceChanged(Camera1.java:75)
	at com.flurgle.camerakit.PreviewImpl.dispatchSurfaceChanged(PreviewImpl.java:37)
	at com.flurgle.camerakit.TextureViewPreview.dispatchSurfaceChanged(TextureViewPreview.java:80)
	at com.flurgle.camerakit.TextureViewPreview$1.onSurfaceTextureAvailable(TextureViewPreview.java:26)
	at android.view.TextureView.getHardwareLayer(TextureView.java:368)
	at android.view.View.updateDisplayListIfDirty(View.java:15261)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.updateDisplayListIfDirty(View.java:15279)
	at android.view.View.draw(View.java:16072)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3622)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3409)
	at android.view.View.draw(View.java:16305)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2771)
	at android.view.View.updateDisplayListIfDirty(View.java:15284)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:295)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:301)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:345)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2686)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2495)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2120)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1138)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6227)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:884)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:870)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:682)
```

**Comment by dwillmc** [comment]
This should be fixed now with the latest release. Can you update your `build.gradle` to reference `com.wonderkiln:camerakit:0.11.1`. If the issue persists can you please re-open.

Thanks!
