### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by capezzbr** [wonderkiln/CameraKit-Android#153]
Got a bunch of crashes from Fabric, latest lib:

```
Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1996)
       at com.flurgle.camerakit.Camera1.openCamera(Camera1.java:315)
       at com.flurgle.camerakit.Camera1.start(Camera1.java:85)
       at com.flurgle.camerakit.CameraView$3.run(CameraView.java:216)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by bdon** [comment]
I've also seen this happen maybe 1 in 50 times, using the CameraView via declaring it in XML
