### ISSUE TITLE
File video is null after video taken

### ISSUE THREAD

**Issue by boranyldrm** [wonderkiln/CameraKit-Android#196]
What can be the problem about it? 
Emulator: Nexus 5X API 23 Android 6.0

_Today I updated build.gradle from "com.flurgle:camerakit:0.9.17"  to "com.wonderkiln:camerakit:0.11.1"  and then this error was occured._

**CODE:**
```
camera.setCameraListener(new CameraListener() {
    @Override
    public void onVideoTaken(File video) {
        super.onVideoTaken(video);
        System.out.println(video.getAbsolutePath());
    }
});

camera.startRecordingVideo();
    camera.postDelayed(new Runnable() {
        @Override
        public void run() {
            camera.stopRecordingVideo();
        }
}, 3000);
```
**ERROR:**
> FATAL EXCEPTION: main
                                                                      Process: co.project.project, PID: 25823
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
                                                                          at co.project.project.Camera.CameraFragment$2.onVideoTaken(CameraFragment.java:123)
                                                                          at com.wonderkiln.camerakit.CameraView$CameraListenerMiddleWare.onVideoTaken(CameraView.java:543)
                                                                          at com.wonderkiln.camerakit.Camera1.endVideo(Camera1.java:335)
                                                                          at com.wonderkiln.camerakit.CameraView.stopRecordingVideo(CameraView.java:450)
                                                                          at co.project.project.Camera.CameraFragment$3.run(CameraFragment.java:131)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by austinkettner** [comment]
Should be resolved in 0.11.2, please comment if you still experience this! We do know of some cases where it is still occurring and will be further resolving in 0.12.0

@boranyldrm
