### ISSUE TITLE
CameraKitView Issues on 1.0.0

### ISSUE THREAD

**Issue by jdcaperon** [wonderkiln/CameraKit-Android#409]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

Yes.

### Environment

Development:
Android Studio 3.1.4
Build #AI-173.4907809, built on July 24, 2018
JRE: 1.8.0_152-release-1024-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-37-generic

Debugging:
Samsung Galaxy S8+
Android 8.0.0

### Steps to Reproduce

1. Create new project.
2. Add gradle dependencies.
3. Copy paste code from 1.0.0 PR to create a 1:1 aspect ratio preview.

### Expected Behavior

The project should build to phone.

### Actual Behavior

```
error: '1:1' is incompatible with attribute com.example.jam.camerakitbug:camera_aspectRatio (attr) float [weak].
Message{kind=ERROR, text=error: '1:1' is incompatible with attribute com.example.jam.camerakitbug:camera_aspectRatio (attr) float [weak]., sources=[/home/jam/Documents/CameraKitBug/app/src/main/res/layout/activity_main.xml:9], original message=, tool name=Optional.of(AAPT)}
```
In the layout editor the following error is also given.

```
java.lang.ClassFormatError: Code attribute in native or abstract methods in class file com/camerakit/CameraKitView$CameraPreview
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.android.tools.idea.rendering.RenderClassLoader.defineClassAndPackage(RenderClassLoader.java:197)
	at com.android.tools.idea.rendering.RenderClassLoader.loadClassFromJar(RenderClassLoader.java:97)
	at org.jetbrains.android.uipreview.ModuleClassLoader.load(ModuleClassLoader.java:170)
	at com.android.tools.idea.rendering.RenderClassLoader.findClass(RenderClassLoader.java:61)
	at org.jetbrains.android.uipreview.ModuleClassLoader.findClass(ModuleClassLoader.java:118)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jetbrains.android.uipreview.ModuleClassLoader.loadClass(ModuleClassLoader.java:213)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:412)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:264)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:222)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:209)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:337)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:348)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:248)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:863)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:544)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:678)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Reproducible Demo

https://github.com/jdcaperon/CameraKitBugDemo

**Comment by emersoncloud** [comment]
Hey @jdcaperon sorry I missed this issue when I responded to your other comment. I'll look into this and get back to you!
