### ISSUE TITLE
Crash: Camera is being used after Camera.release()

### ISSUE THREAD

**Issue by usmanrana07** [wonderkiln/CameraKit-Android#468]
I'm getting following crash sometimes, The scenario is that when image or video is captured then  user is taken to next screen and in onStop method i stop the camera. Sometimes if i perform capturing or recording too frequently by goind back and forth from between camera and next screen. Then app crashes and gives following logs:
```
Fatal Exception: java.lang.RuntimeException: Camera is being used after Camera.release() was called
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:1952)
       at com.wonderkiln.camerakit.Camera1$6.onPreviewFrame(Camera1.java:449)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1133)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by austinkettner** [comment]
This is a known issue and we have an entirely new state-management system coming in our next release to resolve this once and for all. Thanks for creating this ticket @usmanrana07

**Comment by moorthysubu** [comment]
@austinkettner Still getting this error, Is it fixed?
