### ISSUE TITLE
SetPreviewTexture failed on Asus device

### ISSUE THREAD

**Issue by vagnercazarotto** [wonderkiln/CameraKit-Android#502]
### Is this a bug report?
yes

### Have you read the [Contributing Guidelines](.github/CONTRIBUTING.md)?

yes

### Environment
Android 5 in a Asus Z00AD (but also is happening in other Asus devices) 

### Steps to Reproduce
 The error happens when I try to open the camera preview.

`    java.lang.RuntimeException: java.io.IOException: setPreviewTexture failed
        at com.wonderkiln.camerakit.Camera1.setupPreview(Camera1.java:700)
        at com.wonderkiln.camerakit.Camera1.access$200(Camera1.java:37)
        at com.wonderkiln.camerakit.Camera1$1.onSurfaceChanged(Camera1.java:108)
        at com.wonderkiln.camerakit.PreviewImpl.dispatchSurfaceChanged(PreviewImpl.java:38)
        at com.wonderkiln.camerakit.SurfaceViewPreview$2.surfaceChanged(SurfaceViewPreview.java:47)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:590)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5253)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
     Caused by: java.io.IOException: setPreviewTexture failed
        at android.hardware.Camera.setPreviewSurface(Native Method)
        at android.hardware.Camera.setPreviewDisplay(Camera.java:712)
        at com.wonderkiln.camerakit.Camera1.setupPreview(Camera1.java:698)
        at com.wonderkiln.camerakit.Camera1.access$200(Camera1.java:37) 
        at com.wonderkiln.camerakit.Camera1$1.onSurfaceChanged(Camera1.java:108) 
        at com.wonderkiln.camerakit.PreviewImpl.dispatchSurfaceChanged(PreviewImpl.java:38) 
        at com.wonderkiln.camerakit.SurfaceViewPreview$2.surfaceChanged(SurfaceViewPreview.java:47) 
        at android.view.SurfaceView.updateWindow(SurfaceView.java:590) 
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176) 
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847) 
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956) 
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054) 
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
        at android.view.Choreographer.doFrame(Choreographer.java:550) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5253) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)`

**Comment by emersoncloud** [comment]
Thanks for the issue. Looking into it now. Can you send us some more information about your CameraKit setup?

1. CameraKit version you are using. e.g. `0.13.4`, `v1.0.0-beta3.11`
2. CameraKit code you're running in trying to open the preview.

Thanks again!

**Comment by vagnercazarotto** [comment]
> 2\. n

Hello Emerson, Thank you for the help.

So I'm using the version 0.13.5 now, I saw that in this release we have a bug fix for old version in Android and also I can confirm that it solved a lot of crash in the Huawei devices.

I'm using this code above to start the preview act.

`    protected void initCamera() {
        mCameraView = findViewById(R.id.camera_view);
        mCameraView.setPermissions(CameraKit.Constants.PERMISSIONS_PICTURE);
        mCameraView.setCropOutput(true);
        mCameraView.setFlash(CameraKit.Constants.FLASH_OFF);
        mCameraView.setFocus(CameraKit.Constants.FOCUS_CONTINUOUS);
        mCameraView.setPinchToZoom(false);
        mCameraView.setJpegQuality(80);
        mCameraView.setFacing(CameraKit.Constants.FACING_BACK);
    }`

the normal code for start and stop:

`    @Override
    protected void onResume() {
        super.onResume();
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED) {
            mCameraView.start();
        }
    }

    @Override
    protected void onPause() {
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA) == PackageManager.PERMISSION_GRANTED) {
            mCameraView.stop();
        }
        super.onPause();
    }`

check and enable flash:

`    @Override
    public void onToolbarEndButtonClick() {
        mIsFlashEnabled = !mIsFlashEnabled;
        mCameraView.setFlash(mIsFlashEnabled ? CameraKit.Constants.FLASH_ON : CameraKit.Constants.FLASH_OFF);
        changeFlashIcon();
    }
`

I have the clean component for the view:

`    <com.wonderkiln.camerakit.CameraView
        android:id="@+id/camera_view"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:adjustViewBounds="true"
        app:layout_constraintBottom_toTopOf="@id/bottom_bar"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@id/progress_bar" />`


I have the take photo act, but the crash happens before, when we are starting the preview:

`    private void takePhoto() {
        mCameraView.captureImage(new CameraKitEventCallback<CameraKitImage>() {
            @Override
            public void callback(CameraKitImage bitmapPhoto) {
                if (bitmapPhoto != null && bitmapPhoto.getBitmap() != null) {
                    new ResizeBitmapTask(bitmapPhoto.getBitmap(),
                            mCameraView.getWidth(),
                            mCameraView.getHeight(),
                            mDocumentShapeImageView.getX(),
                            ((mDocumentShapeImageView.getY() - mCameraView.getY() >= 0) ? (mDocumentShapeImageView.getY() - mCameraView.getY()) : (mCameraView.getY() - mDocumentShapeImageView.getY())),
                            mDocumentShapeImageView.getWidth(),
                            mDocumentShapeImageView.getHeight(),
//                            bitmapPhoto.rotationDegrees,
                            StepDocumentCamera.this)
                            .execute();
                } else {
                    showGenericPhotoProblemError();
                }
                hideLoadingDialog();
            }
        });

        showLoadingDialog();
    }
`




Anyway if you need something more I can provide.  Thanks
