### ISSUE TITLE
App crashes after i focus with marker for a while

### ISSUE THREAD

**Issue by rohansood42** [wonderkiln/CameraKit-Android#80]
`05-01 21:30:20.250 27560-27560/rohansood.yolo.com.cameratest2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: rohansood.yolo.com.cameratest2, PID: 27560
                                                                                java.lang.RuntimeException: setParameters failed
                                                                                    at android.hardware.Camera.native_setParameters(Native Method)
                                                                                    at android.hardware.Camera.setParameters(Camera.java:1972)
                                                                                    at com.flurgle.camerakit.Camera1$4.onTouch(Camera1.java:515)
                                                                                    at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                                    at com.flurgle.camerakit.CameraView$2.onTouch(CameraView.java:131)
                                                                                    at android.view.View.dispatchTouchEvent(View.java:9300)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                                                    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                                    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2820)
                                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                                                    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                                    at android.view.View.dispatchPointerEvent(View.java:9526)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4267)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4133)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3819)
                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3876)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3727)
                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3693)
                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3701)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3674)
                                                                                    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5959)
                                                                                    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5933)
                                                                                    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5894)
                                                                                    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6062)
                                                                                    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                                    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
                                                                                    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6033)
                                                                                    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6085)
                                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                                                	at android.view.Cho`

The app returns this error after i keep trying to focus for a while.

**Comment by dwillmc** [comment]
This should be fixed now with the latest release. Can you update your `build.gradle` to reference `com.wonderkiln:camerakit:0.11.1`. If the issue persists can you please re-open.

Thanks!
