### ISSUE TITLE
camerakit:ckFocus="tapWithMarker"

### ISSUE THREAD

**Issue by 2astm** [wonderkiln/CameraKit-Android#84]
When I touch in the left top
java.lang.RuntimeException: setParameters failed
                                                       at android.hardware.Camera.native_setParameters(Native Method)
                                                       at android.hardware.Camera.setParameters(Camera.java:1999)
                                                       at com.flurgle.camerakit.Camera1$4.onTouch(Camera1.java:515)
                                                       at android.view.View.dispatchTouchEvent(View.java:9300)
                                                       at com.flurgle.camerakit.CameraView$2.onTouch(CameraView.java:131)
                                                       at android.view.View.dispatchTouchEvent(View.java:9300)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2405)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2820)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2366)
                                                       at android.view.View.dispatchPointerEvent(View.java:9526)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4262)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4128)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3814)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3871)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3722)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3688)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3696)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3669)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5954)
                                                       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5928)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5889)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6057)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                   	at android.app.ActivityThread.main(ActivityThread.java:5

**Comment by dwillmc** [comment]
This should be fixed now with the latest release. Can you update your `build.gradle` to reference `com.wonderkiln:camerakit:0.11.1`. If the issue persists can you please re-open.

Thanks!
